# Generated by Django 5.2.17 on 2026-10-01 23:08

import crm.normalize
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="عنوان فیلد"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع فیلد اضافه",
                "verbose_name_plural": "انواع فیلد اضافه",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="نام"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نام خانوادگی"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نام پدر"
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[crm.normalize.validate_national_code],
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[crm.normalize.validate_phone],
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[crm.normalize.validate_phone],
                        verbose_name="شماره تماس دوم",
                    ),
                ),
                (
                    "father_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[crm.normalize.validate_phone],
                        verbose_name="شماره پدر",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="آیدی تلگرام"
                    ),
                ),
                (
                    "instagram_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="آیدی اینستاگرام"
                    ),
                ),
                (
                    "twitter_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="آیدی توییتر (X)"
                    ),
                ),
                (
                    "bale_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="آیدی بله"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[crm.normalize.validate_postal_code],
                        verbose_name="کد پستی",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخاطب",
                "verbose_name_plural": "مخاطبین",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_repr",
                    models.CharField(
                        max_length=255, verbose_name="نام مخاطب (در لحظه ثبت)"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="کلید فیلد"
                    ),
                ),
                ("field_label", models.CharField(max_length=150, verbose_name="فیلد")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "ایجاد"),
                            ("update", "ویرایش"),
                            ("delete", "حذف"),
                        ],
                        max_length=10,
                        verbose_name="عملیات",
                    ),
                ),
                ("old_value", models.TextField(blank=True, verbose_name="مقدار قبلی")),
                ("new_value", models.TextField(blank=True, verbose_name="مقدار جدید")),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان تغییر"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="change_logs",
                        to="crm.contact",
                        verbose_name="مخاطب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سابقه تغییر",
                "verbose_name_plural": "سوابق تغییرات",
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ExtraValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="مقدار")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_values",
                        to="crm.contact",
                        verbose_name="مخاطب",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm.fielddefinition",
                        verbose_name="فیلد",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات اضافه",
                "verbose_name_plural": "اطلاعات اضافه",
            },
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("national_code", ""), _negated=True),
                fields=("national_code",),
                name="unique_national_code_when_set",
                violation_error_message="مخاطبی با این کد ملی قبلاً ثبت شده است.",
            ),
        ),
        migrations.AddIndex(
            model_name="changelog",
            index=models.Index(
                fields=["contact", "field_name", "changed_at"],
                name="crm_changel_contact_cb5d0e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="extravalue",
            constraint=models.UniqueConstraint(
                fields=("contact", "field"), name="unique_extra_field_per_contact"
            ),
        ),
    ]
