// Builds src/styles/fa.css: Font Awesome's stylesheet with only the icons the site's code uses
// (every "fa-<name>" literal under src/), so the render-blocking stylesheet stays small.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const used = new Set();
(function scan(dir) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) scan(p);
    else if (/\.(tsx?|js)$/.test(f)) for (const m of readFileSync(p, "utf8").matchAll(/fa-[a-z0-9-]+/g)) used.add(m[0]);
  }
})("src");

const css = readFileSync("node_modules/@fortawesome/fontawesome-free/css/all.min.css", "utf8");
const ICON = /^\.fa-[a-z0-9-]+:before$/;
let out = "";
let i = 0;
while (i < css.length) {
  // Split into top-level blocks; @font-face/@keyframes/@media blocks are kept whole.
  const open = css.indexOf("{", i);
  if (open < 0) break;
  let depth = 0;
  let j = open;
  for (; j < css.length; j++) {
    if (css[j] === "{") depth++;
    else if (css[j] === "}" && --depth === 0) break;
  }
  const selector = css.slice(i, open).trim();
  const block = css.slice(open, j + 1);
  const parts = selector.split(",");
  if (parts.every((s) => ICON.test(s))) {
    const keep = parts.filter((s) => used.has(s.slice(1, -":before".length)));
    if (keep.length) out += keep.join(",") + block;
  } else {
    out += selector.replace(/url\(\.\.\/webfonts\/[\w-]+\.ttf\) format\("truetype"\),?/g, "") + block.replace(/,url\(\.\.\/webfonts\/[\w-]+\.ttf\) format\("truetype"\)/g, "");
  }
  i = j + 1;
}
writeFileSync("src/styles/fa.css", `/* Generated by scripts/fa-subset.mjs from @fortawesome/fontawesome-free — do not edit. */\n${out}\n`);
console.log(`fa.css: ${used.size} icon names used, ${(out.length / 1024).toFixed(1)} KB`);
